output_dir: tmp # Output will be written in this directory
virb_path: sample_data   # Input files will be taken from this directory

delete_source_files: N # Y to delete source files after processing,  N to not delete them; remove this line if you want to be prompted.

duration: 60   # how long will the output video be (in seconds)
leadtime: 45  # seconds before the photo
