duration: 4   # how long will the output video be (in seconds)
leadtime: 45  # seconds before the photo
output_dir: /Users/tkla/Dropbox (Personal)/VIRB takeouts
virb_path: /Users/tkla/Desktop/VIRB dump 20171027/
